application: szilardhuber
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /.*
  script: main.app
  secure: optional

libraries:
- name: django
  version: "1.2"
