application: szilardhuber
version: dev-1-04
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: static/images

- url: /stylesheets
  static_dir: static/stylesheets

- url: /js
  static_dir: static/js

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /[uU]ser/.*
  script: userApp.app
  secure: always

- url: .*/[lL]ists.*
  script: listApp.app
  secure: always

- url: .*/[pP]roducts.*
  script: productsApp.app
  secure: always

- url: /admin
  script: adminApp.app
  login: admin

- url: /admin/worker
  script: adminApp.app
  login: admin

- url: /test.*
  script: gaeunitApp.app

- url: /.*
  script: mainApp.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: django
  version: "1.2"
- name: pycrypto
  version: "2.6"

builtins:
- appstats: on