application: szilardhuber
version: dev-1-03
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: static/images

- url: /stylesheets
  static_dir: static/stylesheets
  
- url: /js
  static_dir: static/js
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /[uU]ser/.*
  script: userApp.app
  secure: always

- url: /test.*
  script: gaeunitApp.app
  
- url: /.*
  script: mainApp.app
  secure: optional

libraries:
- name: jinja2
  version: "2.6"
- name: django
  version: "1.2"
- name: pycrypto
  version: "2.6"

builtins:
- appstats: on