application: szilardhuber
version: dev-1-04
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: static/images

- url: /stylesheets
  static_dir: static/stylesheets

- url: /js
  static_dir: static/js

- url: /partials
  static_dir: static/partials

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /[uU]ser/.*
  script: apps.users.app
  secure: always

- url: .*/sessions.*
  script: apps.sessions.app
  secure: always

- url: .*/[lL]ists.*
  script: apps.lists.app
  secure: always

- url: .*/[pP]roducts.*
  script: apps.products.app
  secure: always

- url: /admin
  script: apps.admin.app
  login: admin

- url: /admin/worker
  script: apps.admin.app
  login: admin

- url: /lib/web
  static_dir: lib/bower_components

- url: /.*
  script: apps.main.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: django
  version: "1.2"
- name: pycrypto
  version: "2.6"

builtins:
- appstats: on