application: szilardhuber
version: dev-1-03
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /images
  static_dir: images
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /admin/.*
  script: admin.app
  secure: optional
  login: admin

- url: /[uU]ser/.*
  script: user.app
  secure: always

- url: /test.*
  script: gaeunit.py
  
- url: /.*
  script: main.app
  secure: optional

libraries:
- name: django
  version: "1.2"

